select SUBSTR( DECODE( C8_TIPO,
               'MP','MP '||C8_CODIGO,
                C8_TIPO ),1,10) Codigo_Item,  
       C8_CODIGO, C8_GUIA, C8_TIPO, 
       decode( C8_TIPO,
               'AH',1 ) Count_AH,
       decode( C8_TIPO, 
               'SF',1 ) Count_SF,   
       decode( C8_TIPO,
               'ME',1,
               'ST',1,
               'M2',1,
               'NC',1,  
               'R2',1,
               'A2',1,
               'C2',1,
               'CH',1,
               'AB',1,
               'AL',1,
               'SC',1 ) Count_ME,  
       SUBSTR( C8_DESCRIPCION,1,40) Descripcion,   
       DECODE(UPPER(C6_LxUnidad),
                    'X',C8_UNIDADES,
                    TO_NUMBER(NULL) ) Unidades, 
       DECODE(UPPER(C6_LxPeso),
               'X',C8_PESO, 
                TO_NUMBER(NULL) ) Peso_Item,
       C8_PESO_GUIA  Peso_Guia,
       C8_PRECIO,
       ROUND( DECODE(C6_FxPeso,
                      'X',nvl(TRUNC(C8_UNIDADES*trunc(C8_PESO,3),2)*trunc(C8_PRECIO,3),0),
                          nvl(TRUNC(C8_UNIDADES*1,2)*trunc(C8_PRECIO,3),0) ),2 ) Total_Precio,
       NVL(C8_FLETE,0) C_FLETE,
       ROUND( DECODE(C6_FxPeso,
                      'X',nvl(TRUNC(C8_UNIDADES*trunc(C8_PESO,3),2)*trunc(C8_PRECIO,3),0),
                          nvl(TRUNC(C8_UNIDADES*1,2)*trunc(C8_PRECIO,3),0) ),2) Total_Bs,
       ( decode(C8_CODIGO,'2.1313.45.120',C8_AJUSTE,0) + decode(C8_CODIGO,'2.1515.34.100',C8_AJUSTE,0) ) as AjusteServAsoc,  
       C8_FACTURA
from   INV08_DAT, INV06_DAT
where  C8_TIPO = C6_TIPO
order  by C8_GUIA
